# SPDX-FileCopyrightText: 2023 Kamila Borowska <kamila@borowska.pw>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

name: Renovate Dry Run
on:
  push:
    branches:
      - renovate/*
  pull_request:
    branches:
      - master
env:
  RENOVATE_VERSION: 37.65.2@sha256:44f201002cbdf5894a5f499c1f950b46e65cf9c89df9e04a3e1fa93b82c8952e
jobs:
  renovate-dry-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: renovatebot/github-action@9c2e6e7dc5340821aa2c82094e7326895c94a435 # v39.1.3
        with:
          configurationFile: config.js
          token: ${{ secrets.github_token }}
          renovate-version: ${{ env.RENOVATE_VERSION }}
        env:
          RENOVATE_DRY_RUN: full
