# SPDX-FileCopyrightText: 2023 Kamila Borowska <kamila@borowska.pw>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

name: Renovate
concurrency: renovate
on:
  push:
    branches:
      - master
  schedule:
    - cron: 0/15 * * * *
env:
  RENOVATE_VERSION: 37.261.0@sha256:7deb8c4bf5806f640f1f1645dd53c5aea4e600e43d1c72f51f98d7a664d264fb
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a # v2.1.0
        id: get_token
        with:
          private_key: ${{ secrets.private_key }}
          app_id: ${{ secrets.app_id }}
      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
      - uses: renovatebot/github-action@89bd050bafa5a15de5d9383e3129edf210422004 # v40.1.5
        with:
          configurationFile: config.js
          token: '${{ steps.get_token.outputs.token }}'
          renovate-version: ${{ env.RENOVATE_VERSION }}
