# SPDX-FileCopyrightText: 2023 Konrad Borowski <konrad@borowski.pw>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

name: Renovate
concurrency: renovate
on:
  push:
    branches:
      - master
  schedule:
    - cron: 0/15 * * * *
env:
  RENOVATE_VERSION: 37.26.0@sha256:9efc38ab46fc35337b60161645db2a060aefe8c346951b4280161bc78c1d3abd
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a # v2.1.0
        id: get_token
        with:
          private_key: ${{ secrets.private_key }}
          app_id: ${{ secrets.app_id }}
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
      - uses: renovatebot/github-action@89c8a9b60f5bc8395658abab8f40f96e4b490ebf # v39.1.0
        with:
          configurationFile: config.js
          token: '${{ steps.get_token.outputs.token }}'
          renovate-version: ${{ env.RENOVATE_VERSION }}
