# SPDX-FileCopyrightText: 2023 Kamila Borowska <kamila@borowska.pw>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

name: Renovate Dry Run
on:
  pull_request:
    branches: master
env:
  RENOVATE_VERSION: 37.52.0@sha256:ab5b84456de2baa9c124d4b1ff6a2d9d59233a99d39f9661bc2385ff381b5bda
jobs:
  renovate-dry-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: renovatebot/github-action@5c6c06aa0e3d7a6a9b6cba05c078c51631b5f11a # v39.1.1
        with:
          configurationFile: config.js
          token: ${{ secrets.github_token }}
          renovate-version: ${{ env.RENOVATE_VERSION }}
        env:
          RENOVATE_DRY_RUN: full
