# SPDX-FileCopyrightText: 2023 Konrad Borowski <konrad@borowski.pw>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

name: Renovate Dry Run
on:
  pull_request:
    branches: master
env:
  RENOVATE_VERSION: 37.44.0@sha256:26dd8d3be47266055006dc7310bd17b294c289856408a522d84e47e4bcb78647
jobs:
  renovate-dry-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: renovatebot/github-action@5c6c06aa0e3d7a6a9b6cba05c078c51631b5f11a # v39.1.1
        with:
          configurationFile: config.js
          token: ${{ secrets.github_token }}
          renovate-version: ${{ env.RENOVATE_VERSION }}
        env:
          RENOVATE_DRY_RUN: full
