# SPDX-FileCopyrightText: 2023 Kamila Borowska <kamila@borowska.pw>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

name: Renovate Dry Run
on:
  push:
    branches:
      - renovate/*
  pull_request:
    branches:
      - master
env:
  RENOVATE_VERSION: 37.221.3@sha256:fb58f9ff009135a0238b70d18032715c73f7a9d27f409c781cd3578dbcb6ea6a
jobs:
  renovate-dry-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: renovatebot/github-action@8f6b0f762415909f60b0efb1817c4dee029ea806 # v40.1.1
        with:
          configurationFile: config.js
          token: ${{ secrets.github_token }}
          renovate-version: ${{ env.RENOVATE_VERSION }}
        env:
          RENOVATE_DRY_RUN: full
