# SPDX-FileCopyrightText: 2023 Kamila Borowska <kamila@borowska.pw>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

name: Renovate
concurrency: renovate
on:
  push:
    branches:
      - master
  schedule:
    - cron: 0/15 * * * *
env:
  RENOVATE_VERSION: 37.269.3@sha256:0cf239fb4c133aa08d61c6b5d0c57ba7146b94d2cd589c55db4438139f796b6d
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a # v2.1.0
        id: get_token
        with:
          private_key: ${{ secrets.private_key }}
          app_id: ${{ secrets.app_id }}
      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
      - uses: renovatebot/github-action@23b01dbf6f38965076a36aff87f802263164f204 # v40.1.6
        with:
          configurationFile: config.js
          token: '${{ steps.get_token.outputs.token }}'
          renovate-version: ${{ env.RENOVATE_VERSION }}
