# SPDX-FileCopyrightText: 2023 Kamila Borowska <kamila@borowska.pw>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

name: Renovate Dry Run
on:
  push:
    branches:
      - renovate/*
  pull_request:
    branches:
      - master
env:
  RENOVATE_VERSION: 37.269.4@sha256:cb66a4844111f3a6065a716b7b8a3da8bc8eff04b6f89922b1f26e6d39639496
jobs:
  renovate-dry-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
      - uses: renovatebot/github-action@89bd050bafa5a15de5d9383e3129edf210422004 # v40.1.5
        with:
          configurationFile: config.js
          token: ${{ secrets.github_token }}
          renovate-version: ${{ env.RENOVATE_VERSION }}
        env:
          RENOVATE_DRY_RUN: full
