# SPDX-FileCopyrightText: 2023 Kamila Borowska <kamila@borowska.pw>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

name: Renovate
concurrency: renovate
on:
  push:
    branches:
      - master
  schedule:
    - cron: 0/15 * * * *
env:
  RENOVATE_VERSION: 37.222.3@sha256:cc71790df21b456d18a55a1719d48e7229736bc99ae7cdd3395cc6f4f7c8be33
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a # v2.1.0
        id: get_token
        with:
          private_key: ${{ secrets.private_key }}
          app_id: ${{ secrets.app_id }}
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: renovatebot/github-action@8f6b0f762415909f60b0efb1817c4dee029ea806 # v40.1.1
        with:
          configurationFile: config.js
          token: '${{ steps.get_token.outputs.token }}'
          renovate-version: ${{ env.RENOVATE_VERSION }}
